"use client";

import Link from "next/link";
import { useMemo, useState } from "react";
import { ChevronLeft, ChevronRight } from "lucide-react";
import { Button, Card, CardHeader, EmptyState } from "@/components/ui";
import type { LeaveEntry, Person, SchedulePhaseView } from "@/lib/data/types";

type CalendarView = "day" | "week" | "month";
const weekdays = ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"];

export function PhaseCalendar({ phases, people, leave = [], mode = "calendar", title: heading = "Calendar", description = "Project Call-Ups scheduled against each assigned user.", onSiteAssignmentKeys = [] }: { phases: SchedulePhaseView[]; people: Person[]; leave?: LeaveEntry[]; mode?: "calendar" | "field"; title?: string; description?: string; onSiteAssignmentKeys?: string[] }) {
  const [view, setView] = useState<CalendarView>("week");
  const [anchor, setAnchor] = useState(() => new Date());
  const days = useMemo(() => visibleDays(view, anchor), [view, anchor]);
  const rangeLabel = view === "day" ? anchor.toLocaleDateString("en-AU", { weekday: "long", day: "numeric", month: "long", year: "numeric" }) : view === "week" ? `${days[0].toLocaleDateString("en-AU", { day: "numeric", month: "short" })} – ${days.at(-1)!.toLocaleDateString("en-AU", { day: "numeric", month: "short", year: "numeric" })}` : anchor.toLocaleDateString("en-AU", { month: "long", year: "numeric" });
  const phaseMap = new Map<string, SchedulePhaseView[]>();
  for (const phase of phases) { const list = phaseMap.get(phase.date) ?? []; list.push(phase); phaseMap.set(phase.date, list); }
  const leaveMap = new Map<string, LeaveEntry[]>();
  for (const entry of leave.filter(isActiveUnavailability)) for (const day of leaveDays(entry, days)) { const list = leaveMap.get(day) ?? []; list.push(entry); leaveMap.set(day, list); }
  const peopleById = new Map(people.map((person) => [person.id, person]));
  function move(offset: number) { setAnchor((current) => addDays(current, view === "day" ? offset : view === "week" ? offset * 7 : offset * 31)); }

  return <div className="space-y-4"><Card><CardHeader title={heading} description={description} action={<div className="flex items-center gap-1"><Button size="sm" variant="ghost" aria-label="Previous" onClick={() => move(-1)}><ChevronLeft className="size-4" /></Button><Button size="sm" variant="ghost" onClick={() => setAnchor(new Date())}>Today</Button><Button size="sm" variant="ghost" aria-label="Next" onClick={() => move(1)}><ChevronRight className="size-4" /></Button></div>} /><div className="flex flex-wrap items-center justify-between gap-3 border-b border-border-subtle px-4 py-3"><p className="text-sm font-bold">{rangeLabel}</p><div className="flex rounded-lg bg-surface-muted p-1">{(["day", "week", "month"] as CalendarView[]).map((option) => <button key={option} type="button" onClick={() => setView(option)} className={`rounded-md px-3 py-1.5 text-xs font-bold capitalize ${view === option ? "bg-surface text-foreground shadow-sm" : "text-muted-foreground"}`}>{option}</button>)}</div></div>{view === "day" ? <DayView phases={phaseMap.get(dateKey(days[0])) ?? []} people={people} leave={leaveMap.get(dateKey(days[0])) ?? []} mode={mode} onSiteAssignmentKeys={onSiteAssignmentKeys} /> : view === "week" ? <WeekView days={days} phaseMap={phaseMap} leaveMap={leaveMap} peopleById={peopleById} mode={mode} onSiteAssignmentKeys={onSiteAssignmentKeys} /> : <MonthView days={days} phaseMap={phaseMap} leaveMap={leaveMap} peopleById={peopleById} currentMonth={anchor.getMonth()} mode={mode} onSiteAssignmentKeys={onSiteAssignmentKeys} />}</Card></div>;
}

function DayView({ phases, people, leave, mode, onSiteAssignmentKeys }: { phases: SchedulePhaseView[]; people: Person[]; leave: LeaveEntry[]; mode: "calendar" | "field"; onSiteAssignmentKeys: string[] }) { const byUser = new Map<string, SchedulePhaseView[]>(); for (const phase of phases) { const rows = byUser.get(phase.userId) ?? []; rows.push(phase); byUser.set(phase.userId, rows); } return <div>{people.length ? people.map((person) => { const unavailable = leave.find((entry) => entry.userId === person.id); const assigned = byUser.get(person.id) ?? []; return <div key={person.id} className="grid min-h-20 grid-cols-[10rem_1fr] border-b border-border-subtle last:border-0"><div className="border-r border-border-subtle bg-surface-muted px-4 py-3"><p className="flex items-center gap-2 text-sm font-bold"><span className="size-2.5 rounded-full" style={{ backgroundColor: person.color ?? userColor(person.id) }} />{person.name}</p><p className="text-xs text-muted-foreground">{unavailable ? "Unavailable" : person.role.replaceAll("_", " ")}</p></div><div className="space-y-2 p-3">{unavailable ? <LeaveCard entry={unavailable} person={person} /> : null}{assigned.map((phase) => <PhaseCard key={phase.id} phase={phase} person={person} mode={mode} onSite={onSiteAssignmentKeys.includes(`${phase.projectId}:${phase.userId}`)} />)}{!unavailable && !assigned.length ? <p className="pt-2 text-sm text-muted-foreground">No scheduled Call-Ups</p> : null}</div></div>; }) : <EmptyState title="No Call-Ups assigned" />}</div>; }

function WeekView({ days, phaseMap, leaveMap, peopleById, mode, onSiteAssignmentKeys }: { days: Date[]; phaseMap: Map<string, SchedulePhaseView[]>; leaveMap: Map<string, LeaveEntry[]>; peopleById: Map<string, Person>; mode: "calendar" | "field"; onSiteAssignmentKeys: string[] }) { const grid = { display: "grid", gridTemplateColumns: "repeat(7, minmax(0, 1fr))" }; return <div className="overflow-x-auto"><div className="min-w-[760px]"><div style={grid} className="border-b border-border-subtle bg-surface-muted">{days.map((day) => <div key={dateKey(day)} className={`border-r border-border-subtle px-3 py-2 text-center text-xs last:border-0 ${sameDay(day, new Date()) ? "font-bold text-primary" : "text-muted-foreground"}`}><span className="block uppercase">{weekdays[day.getDay()]}</span><span className="text-sm text-foreground">{day.getDate()}</span></div>)}</div><div style={grid} className="min-h-[480px]">{days.map((day) => <div key={dateKey(day)} className="border-r border-border-subtle p-2 last:border-0">{(leaveMap.get(dateKey(day)) ?? []).map((entry) => <LeaveCard key={entry.id} entry={entry} person={peopleById.get(entry.userId)} compact />)}{(phaseMap.get(dateKey(day)) ?? []).map((phase) => <PhaseCard key={phase.id} phase={phase} person={peopleById.get(phase.userId)} compact mode={mode} onSite={onSiteAssignmentKeys.includes(`${phase.projectId}:${phase.userId}`)} />)}</div>)}</div></div></div>; }

function MonthView({ days, phaseMap, leaveMap, peopleById, currentMonth, mode, onSiteAssignmentKeys }: { days: Date[]; phaseMap: Map<string, SchedulePhaseView[]>; leaveMap: Map<string, LeaveEntry[]>; peopleById: Map<string, Person>; currentMonth: number; mode: "calendar" | "field"; onSiteAssignmentKeys: string[] }) { const grid = { display: "grid", gridTemplateColumns: "repeat(7, minmax(0, 1fr))" }; return <div className="overflow-x-auto"><div className="min-w-[760px]"><div style={grid} className="border-b border-border-subtle bg-surface-muted">{weekdays.map((weekday) => <div key={weekday} className="border-r border-border-subtle px-3 py-2 text-center text-xs font-bold text-muted-foreground last:border-0">{weekday}</div>)}</div><div style={grid}>{days.map((day) => { const unavailable = leaveMap.get(dateKey(day)) ?? []; const phaseRows = phaseMap.get(dateKey(day)) ?? []; return <div key={dateKey(day)} className={`min-h-28 border-b border-r border-border-subtle p-2 ${day.getMonth() !== currentMonth ? "bg-surface-muted/60" : ""}`}><p className={`mb-1 text-xs font-bold ${sameDay(day, new Date()) ? "text-primary" : "text-muted-foreground"}`}>{day.getDate()}</p>{unavailable.slice(0, 2).map((entry) => <LeaveCard key={entry.id} entry={entry} person={peopleById.get(entry.userId)} compact />)}{phaseRows.slice(0, Math.max(0, 3 - unavailable.length)).map((phase) => <PhaseCard key={phase.id} phase={phase} person={peopleById.get(phase.userId)} compact mode={mode} onSite={onSiteAssignmentKeys.includes(`${phase.projectId}:${phase.userId}`)} />)}{unavailable.length + phaseRows.length > 3 ? <p className="text-[11px] text-muted-foreground">+{unavailable.length + phaseRows.length - 3} more</p> : null}</div>; })}</div></div></div>; }

function PhaseCard({ phase, person, compact = false, mode, onSite = false }: { phase: SchedulePhaseView; person?: Person; compact?: boolean; mode: "calendar" | "field"; onSite?: boolean }) { const color = person?.color ?? userColor(phase.userId); const href = mode === "field" ? `/field/${phase.projectId}` : phase.inspectionId ? `/projects/${phase.projectId}/qa` : `/projects/${phase.projectId}/schedule`; return <Link href={href} style={{ backgroundColor: color, borderColor: color, color: "#fff" }} className={`relative mb-1 block overflow-hidden rounded-md border px-2 py-1.5 shadow-sm transition-opacity hover:opacity-85 ${compact ? "text-[11px]" : "text-sm"} ${onSite ? "onsite-calendar-tile" : ""}`}>{onSite ? <><span className="onsite-calendar-colour-flow" aria-hidden="true" /><span className="onsite-calendar-shimmer" aria-hidden="true" /><span className="onsite-calendar-dot" aria-label="On site" title="On site" /></> : null}<p className="relative z-10 truncate font-bold">{phase.projectTitle} · {phase.title}{onSite ? " · On site" : ""}</p>{compact ? <p className="relative z-10 truncate opacity-85">{person?.name ?? "Unassigned"}</p> : <p className="relative z-10 truncate text-xs opacity-85">{person?.name ?? "Unassigned"}{phase.description ? ` · ${phase.description}` : ""}</p>}</Link>; }
function LeaveCard({ entry, person, compact = false }: { entry: LeaveEntry; person?: Person; compact?: boolean }) { return <div className={`mb-1 rounded-md border border-amber-500/45 bg-amber-500/10 px-2 py-1.5 text-amber-800 dark:text-amber-300 ${compact ? "text-[11px]" : "text-sm"}`}><p className="truncate font-bold">{person?.name ?? "Team member"} · Unavailable</p><p className="truncate text-xs opacity-85">{entry.type.replaceAll("_", " ")}{entry.reason ? ` · ${entry.reason}` : ""}</p></div>; }

function dateKey(date: Date) { return `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, "0")}-${String(date.getDate()).padStart(2, "0")}`; }
function addDays(date: Date, days: number) { const next = new Date(date); next.setDate(next.getDate() + days); return next; }
function startWeek(date: Date) { return addDays(date, -date.getDay()); }
function visibleDays(view: CalendarView, anchor: Date) { if (view === "day") return [anchor]; if (view === "week") return Array.from({ length: 7 }, (_, index) => addDays(startWeek(anchor), index)); const first = new Date(anchor.getFullYear(), anchor.getMonth(), 1); const start = startWeek(first); return Array.from({ length: 42 }, (_, index) => addDays(start, index)); }
function sameDay(left: Date, right: Date) { return dateKey(left) === dateKey(right); }
function isActiveUnavailability(entry: LeaveEntry) { return entry.status !== "cancelled" && entry.status !== "declined"; }
function leaveDays(entry: LeaveEntry, days: Date[]) { const start = availabilityDate(entry.startsAt); const end = availabilityDate(entry.endsAt); return days.map(dateKey).filter((day) => day >= start && day <= end); }
function availabilityDate(value: string) { return value.length === 10 ? value : dateKey(new Date(value)); }
function userColor(userId: string) { const colors = ["#2563eb", "#7c3aed", "#db2777", "#d97706", "#059669", "#0891b2", "#4f46e5", "#be123c"]; let hash = 0; for (const character of userId) hash = (hash * 31 + character.charCodeAt(0)) >>> 0; return colors[hash % colors.length]; }
