"use client";

import { useActionState, useState } from "react";
import { saveLabourSettings, type LabourActionState } from "@/app/actions/labour";
import { Button, Card, CardHeader } from "@/components/ui";
import type { CatalogueMaterial, LabourSettings } from "@/lib/data/types";

const initial: LabourActionState = { ok: false };
const inputClass = "h-11 w-full rounded-lg border border-border-strong bg-surface px-3 text-sm text-foreground";
function label(material: CatalogueMaterial) { return material.variation ? `${material.name} — ${material.variation}` : material.name; }
function selectableMaterials(materials: CatalogueMaterial[]) { const namesWithVariations = new Set(materials.filter((material) => material.variation).map((material) => material.name)); return materials.filter((material) => material.standardPriceCentsPerM2 > 0 && (material.variation || !namesWithVariations.has(material.name))); }

export function LabourManager({ settings, materials }: { settings: LabourSettings; materials: CatalogueMaterial[] }) {
  const [state, action, pending] = useActionState(saveLabourSettings, initial);
  const [enabled, setEnabled] = useState(settings.standardLabourEnabled);
  const [rates, setRates] = useState<Record<string, string>>(() => Object.fromEntries(settings.subcontractorMaterialRates.map((rate) => [rate.materialId, (rate.costCentsPerM2 / 100).toFixed(2)])));
  const entries = Object.entries(rates).filter(([, value]) => Number(value) > 0).map(([id, value]) => `${id}:${value}`).join("\n");
  const availableMaterials = selectableMaterials(materials);
  return <div className="grid gap-4 xl:grid-cols-2"><Card><CardHeader title="Standard labour" description="A single labour budget cost for each employee assigned to a job. Enable it per project in Costing." /><form action={action} className="space-y-4 p-4"><input type="hidden" name="subcontractorRates" value={entries} /><label className="flex min-h-11 items-center gap-3 rounded-lg border border-border-subtle bg-surface-muted px-3"><input name="standardLabourEnabled" type="checkbox" checked={enabled} onChange={(event) => setEnabled(event.target.checked)} className="size-5 accent-primary" /><span><span className="block text-sm font-bold">Enable standard labour budget</span><span className="block text-xs text-muted-foreground">Projects can then set their employee count.</span></span></label><label className="block text-sm font-semibold">Cost per employee, per job<input name="standardLabourCostPerEmployee" type="number" min="0" step="0.01" defaultValue={settings.standardLabourCostCentsPerEmployee ? (settings.standardLabourCostCentsPerEmployee / 100).toFixed(2) : ""} disabled={!enabled} placeholder="$0.00" className={`${inputClass} mt-1 disabled:opacity-45`} /></label><Button type="submit" variant="primary" disabled={pending}>{pending ? "Saving…" : "Save labour settings"}</Button>{state.message ? <p className="text-xs text-muted-foreground">{state.message}</p> : null}</form></Card><Card><CardHeader title="Subcontractor material rates" description="Set the amount paid to a subcontractor per quoted m². Enable the cost per project in Costing." /><form action={action} className="space-y-3 p-4"><input type="hidden" name="standardLabourEnabled" value={settings.standardLabourEnabled ? "on" : ""} /><input type="hidden" name="standardLabourCostPerEmployee" value={settings.standardLabourCostCentsPerEmployee / 100} /><input type="hidden" name="subcontractorRates" value={entries} /><div className="space-y-2">{availableMaterials.length ? availableMaterials.map((material) => <label key={material.id} className="flex items-center gap-3"><span className="min-w-0 flex-1 truncate text-sm">{label(material)}</span><input type="number" min="0" step="0.01" placeholder="Sub rate $/m²" value={rates[material.id] ?? ""} onChange={(event) => setRates((current) => ({ ...current, [material.id]: event.target.value }))} className="h-11 w-40 rounded-lg border border-border-strong bg-surface px-3 text-sm" /></label>) : <p className="text-sm text-muted-foreground">Add priced materials and variations first.</p>}</div><Button type="submit" variant="primary" disabled={pending}>{pending ? "Saving…" : "Save subcontractor rates"}</Button>{state.message ? <p className="text-xs text-muted-foreground">{state.message}</p> : null}</form></Card></div>;
}
