"use client";

import { useActionState, useState } from "react";
import { addMaterial, addPriceList, type MaterialActionState } from "@/app/actions/materials";
import { Button, Card, CardHeader } from "@/components/ui";
import type { CatalogueMaterial, CustomerPriceList } from "@/lib/data/types";

const initial: MaterialActionState = { ok: false };
const input = "h-11 w-full rounded-lg border border-border-strong bg-surface px-3 text-sm text-foreground";

export function MaterialsManager({ materials, priceLists }: { materials: CatalogueMaterial[]; priceLists: CustomerPriceList[] }) {
  const [materialState, materialAction, materialPending] = useActionState(addMaterial, initial);
  const [listState, listAction, listPending] = useActionState(addPriceList, initial);
  const [prices, setPrices] = useState<Record<string, string>>({});
  const entries = Object.entries(prices).filter(([, value]) => Number(value) > 0).map(([id, value]) => `${id}:${value}`).join("\n");
  return <div className="grid gap-4 xl:grid-cols-2"><Card><CardHeader title="Material catalogue" description="Your internal cost price per square metre." /><form action={materialAction} className="space-y-3 p-4"><div className="grid gap-3 sm:grid-cols-2"><input name="name" required placeholder="Material name" className={input} /><input name="sku" required placeholder="SKU" className={input} /><input name="costPerM2" required type="number" min="0.01" step="0.01" placeholder="Cost per m²" className={input} /><input name="description" placeholder="Description" className={input} /></div><Button type="submit" variant="primary" disabled={materialPending}>{materialPending ? "Adding…" : "Add material"}</Button>{materialState.message ? <p className={materialState.ok ? "text-xs text-[var(--tone-emerald-fg)]" : "text-xs text-[var(--tone-rose-fg)]"}>{materialState.message}</p> : null}</form><div className="divide-y divide-border-subtle">{materials.map((material) => <div key={material.id} className="flex items-center justify-between gap-3 px-4 py-3"><div><p className="text-sm font-bold">{material.name}</p><p className="text-xs text-muted-foreground">{material.sku}{material.description ? ` · ${material.description}` : ""}</p></div><p className="text-sm font-bold tabular-nums">${(material.costCentsPerM2 / 100).toFixed(2)}/m²</p></div>)}</div></Card><Card><CardHeader title="Customer price lists" description="Set customer purchase prices; blank materials use the standard default pricing." /><form action={listAction} className="space-y-3 p-4"><input name="name" required placeholder="Price list name" className={input} /><input type="hidden" name="entries" value={entries} /><div className="space-y-2">{materials.map((material) => <label key={material.id} className="flex items-center gap-3"><span className="min-w-0 flex-1 truncate text-sm">{material.name}</span><input type="number" min="0" step="0.01" placeholder="Customer $/m²" value={prices[material.id] ?? ""} onChange={(event) => setPrices((current) => ({ ...current, [material.id]: event.target.value }))} className="h-10 w-36 rounded-lg border border-border-strong bg-surface px-2 text-sm" /></label>)}</div><Button type="submit" variant="primary" disabled={listPending || !materials.length}>{listPending ? "Saving…" : "Create price list"}</Button>{listState.message ? <p className={listState.ok ? "text-xs text-[var(--tone-emerald-fg)]" : "text-xs text-[var(--tone-rose-fg)]"}>{listState.message}</p> : null}</form><div className="divide-y divide-border-subtle">{priceLists.map((list) => <div key={list.id} className="px-4 py-3"><p className="text-sm font-bold">{list.name}</p><p className="text-xs text-muted-foreground">{list.entries.length} material prices</p></div>)}</div></Card></div>;
}
