"use client";

import { useActionState, useState, useTransition } from "react";
import { useRouter } from "next/navigation";
import { addMaterial, addPriceList, deleteMaterial, deletePriceList, type MaterialActionState, updateMaterial, updatePriceList } from "@/app/actions/materials";
import { Button, Card, CardHeader } from "@/components/ui";
import type { CatalogueMaterial, CustomerPriceList } from "@/lib/data/types";

const initial: MaterialActionState = { ok: false };
const input = "h-10 w-full rounded-lg border border-border-strong bg-surface px-2 text-sm text-foreground";

export function MaterialsManager({ materials, priceLists }: { materials: CatalogueMaterial[]; priceLists: CustomerPriceList[] }) {
  const [materialState, materialAction, materialPending] = useActionState(addMaterial, initial);
  const [listState, listAction, listPending] = useActionState(addPriceList, initial);
  const [prices, setPrices] = useState<Record<string, string>>({});
  const entries = Object.entries(prices).filter(([, value]) => Number(value) > 0).map(([id, value]) => `${id}:${value}`).join("\n");
  return <div className="grid gap-4 xl:grid-cols-2"><Card><CardHeader title="Material catalogue" description="Set the internal cost and standard customer price per square metre." /><form action={materialAction} className="grid gap-2 border-b border-border-subtle p-4 sm:grid-cols-2"><input name="name" required placeholder="Material name" className={input} /><input name="sku" required placeholder="SKU" className={input} /><input name="costPerM2" required type="number" min="0.01" step="0.01" placeholder="Cost per m²" className={input} /><input name="standardPricePerM2" required type="number" min="0.01" step="0.01" placeholder="Standard sell $/m²" className={input} /><input name="description" placeholder="Description" className={input} /><Button type="submit" variant="primary" disabled={materialPending}>{materialPending ? "Adding…" : "Add material"}</Button>{materialState.message ? <p className="self-center text-xs text-muted-foreground">{materialState.message}</p> : null}</form><div className="divide-y divide-border-subtle">{materials.map((material) => <MaterialEditor key={material.id} material={material} />)}</div></Card><Card><CardHeader title="Customer price lists" description="Enter only the prices that differ. Blank prices use the standard material price." /><form action={listAction} className="space-y-3 border-b border-border-subtle p-4"><input name="name" required placeholder="Price list name" className={input} /><input type="hidden" name="entries" value={entries} /><div className="space-y-2">{materials.map((material) => <label key={material.id} className="flex items-center gap-3"><span className="min-w-0 flex-1 truncate text-sm">{material.name}</span><input type="number" min="0" step="0.01" placeholder={`Standard $${(material.standardPriceCentsPerM2 / 100).toFixed(2)}`} value={prices[material.id] ?? ""} onChange={(event) => setPrices((current) => ({ ...current, [material.id]: event.target.value }))} className="h-10 w-36 rounded-lg border border-border-strong bg-surface px-2 text-sm" /></label>)}</div><Button type="submit" variant="primary" disabled={listPending || !materials.length}>{listPending ? "Saving…" : "Create price list"}</Button>{listState.message ? <p className="text-xs text-muted-foreground">{listState.message}</p> : null}</form><div className="divide-y divide-border-subtle">{priceLists.map((list) => <PriceListEditor key={list.id} list={list} materials={materials} />)}</div></Card></div>;
}

function MaterialEditor({ material }: { material: CatalogueMaterial }) { const [editing, setEditing] = useState(false); const [state, action, pending] = useActionState(updateMaterial, initial); const [deleting, start] = useTransition(); const router = useRouter(); if (!editing) return <div className="flex items-center justify-between gap-3 px-4 py-3"><div><p className="text-sm font-bold">{material.name}</p><p className="text-xs text-muted-foreground">{material.sku}{material.description ? ` · ${material.description}` : ""} · Cost ${(material.costCentsPerM2 / 100).toFixed(2)} · Standard ${(material.standardPriceCentsPerM2 / 100).toFixed(2)}/m²</p></div><div className="flex gap-2"><Button size="sm" onClick={() => setEditing(true)}>Edit</Button><Button size="sm" variant="danger" disabled={deleting} onClick={() => { if (window.confirm(`Remove ${material.name}?`)) start(async () => { await deleteMaterial(material.id); router.refresh(); }); }}>Remove</Button></div></div>; return <form action={action} className="grid gap-2 bg-surface-muted p-4 sm:grid-cols-2"><input type="hidden" name="id" value={material.id} /><input name="name" defaultValue={material.name} className={input} /><input name="sku" defaultValue={material.sku} className={input} /><input name="costPerM2" type="number" step="0.01" defaultValue={(material.costCentsPerM2 / 100).toFixed(2)} className={input} /><input name="standardPricePerM2" type="number" step="0.01" defaultValue={(material.standardPriceCentsPerM2 / 100).toFixed(2)} className={input} /><input name="description" defaultValue={material.description ?? ""} className={input} /><div className="flex gap-2"><Button size="sm" type="submit" variant="primary" disabled={pending}>Save</Button><Button size="sm" type="button" variant="ghost" onClick={() => setEditing(false)}>Cancel</Button></div>{state.message ? <p className="text-xs text-muted-foreground">{state.message}</p> : null}</form>; }

function PriceListEditor({ list, materials }: { list: CustomerPriceList; materials: CatalogueMaterial[] }) { const [editing, setEditing] = useState(false); const [state, action, pending] = useActionState(updatePriceList, initial); const [deleting, start] = useTransition(); const router = useRouter(); const [prices, setPrices] = useState<Record<string, string>>(() => Object.fromEntries(list.entries.map((entry) => [entry.materialId, (entry.priceCentsPerM2 / 100).toFixed(2)]))); const entries = Object.entries(prices).filter(([, value]) => Number(value) > 0).map(([id, value]) => `${id}:${value}`).join("\n"); if (!editing) return <div className="flex items-center justify-between gap-3 px-4 py-3"><div><p className="text-sm font-bold">{list.name}</p><p className="text-xs text-muted-foreground">{list.entries.length} customer prices</p></div><div className="flex gap-2"><Button size="sm" onClick={() => setEditing(true)}>Edit</Button><Button size="sm" variant="danger" disabled={deleting} onClick={() => { if (window.confirm(`Remove ${list.name}? Customers will return to default pricing.`)) start(async () => { await deletePriceList(list.id); router.refresh(); }); }}>Remove</Button></div></div>; return <form action={action} className="space-y-2 bg-surface-muted p-4"><input type="hidden" name="id" value={list.id} /><input type="hidden" name="entries" value={entries} /><input name="name" defaultValue={list.name} className={input} />{materials.map((material) => <label key={material.id} className="flex items-center gap-3"><span className="min-w-0 flex-1 truncate text-sm">{material.name}</span><input type="number" step="0.01" placeholder={`Standard $${(material.standardPriceCentsPerM2 / 100).toFixed(2)}`} value={prices[material.id] ?? ""} onChange={(event) => setPrices((current) => ({ ...current, [material.id]: event.target.value }))} className="h-10 w-32 rounded-lg border border-border-strong bg-surface px-2 text-sm" /></label>)}<p className="text-xs text-muted-foreground">Leave a price blank to use the standard material price.</p><div className="flex gap-2"><Button size="sm" type="submit" variant="primary" disabled={pending}>Save</Button><Button size="sm" type="button" variant="ghost" onClick={() => setEditing(false)}>Cancel</Button></div>{state.message ? <p className="text-xs text-muted-foreground">{state.message}</p> : null}</form>; }
