"use client";

import { useActionState, useState, useTransition } from "react";
import { useRouter } from "next/navigation";
import { Plus, Trash2 } from "lucide-react";
import { addLeave, addPerson, deleteLeave, deletePerson, type PeopleActionState, updateLeave, updatePerson } from "@/app/actions/people";
import { Button, Card, CardHeader, EmptyState } from "@/components/ui";
import type { LeaveEntry, Person } from "@/lib/data/types";
import { formatDate } from "@/lib/utils";

const initial: PeopleActionState = { ok: false };
const inputClass = "h-11 w-full rounded-lg border border-border-strong bg-surface px-3 text-sm text-foreground";
type Option = { id: string; label: string };

export function PeopleManager({ people, leave, canManage, roles, leaveTypes, leaveStatuses }: { people: Person[]; leave: LeaveEntry[]; canManage: boolean; roles: Option[]; leaveTypes: Option[]; leaveStatuses: Option[] }) {
  const [addingPerson, setAddingPerson] = useState(false); const [addingLeave, setAddingLeave] = useState(false);
  return <div className="grid gap-4 lg:grid-cols-2"><Card><CardHeader title="Team" description="People, roles, cost rates, availability and calendar colour." action={canManage ? <Button size="sm" variant="primary" onClick={() => setAddingPerson(true)}><Plus className="size-4" /> Add person</Button> : null} />{addingPerson ? <PersonForm roles={roles} onClose={() => setAddingPerson(false)} /> : null}{people.length ? <div className="divide-y divide-border-subtle">{people.map((person) => <PersonRow key={person.id} person={person} canManage={canManage} roles={roles} />)}</div> : <EmptyState title="No people yet" />}</Card><Card><CardHeader title="Leave & unavailability" description="Leave and unavailable time can be managed here." action={canManage ? <Button size="sm" variant="primary" onClick={() => setAddingLeave(true)}><Plus className="size-4" /> Add availability</Button> : null} />{addingLeave ? <LeaveForm people={people} leaveTypes={leaveTypes} leaveStatuses={leaveStatuses} onClose={() => setAddingLeave(false)} /> : null}{leave.length ? <div className="divide-y divide-border-subtle">{leave.map((entry) => <LeaveRow key={entry.id} entry={entry} people={people} canManage={canManage} leaveTypes={leaveTypes} leaveStatuses={leaveStatuses} />)}</div> : <EmptyState title="No leave or unavailability recorded" />}</Card></div>;
}

function PersonRow({ person, canManage, roles }: { person: Person; canManage: boolean; roles: Option[] }) { const [editing, setEditing] = useState(false); const [deleting, startTransition] = useTransition(); const router = useRouter(); if (editing) return <PersonForm person={person} roles={roles} onClose={() => setEditing(false)} />; return <div className="flex flex-wrap items-center justify-between gap-3 px-4 py-4"><div className="flex min-w-0 items-center gap-3"><span className="size-10 shrink-0 rounded-full" style={{ backgroundColor: person.color ?? defaultColor(person.id) }} /><div className="min-w-0"><p className="truncate text-sm font-bold">{person.name}</p><p className="truncate text-xs text-muted-foreground">{person.email} · {roles.find((role) => role.id === person.role)?.label ?? person.role}{person.isSchedulable ? " · Schedulable" : ""}</p></div></div>{canManage ? <div className="flex gap-2"><Button size="sm" onClick={() => setEditing(true)}>Edit</Button><Button size="sm" variant="danger" disabled={deleting} onClick={() => { if (window.confirm(`Delete ${person.name}? Their leave, assignments, time entries, and calendar Call-Ups will be removed.`)) startTransition(async () => { await deletePerson(person.id); router.refresh(); }); }}><Trash2 className="size-3.5" /> Delete</Button></div> : null}</div>; }

function PersonForm({ person, roles, onClose }: { person?: Person; roles: Option[]; onClose: () => void }) { const [state, action, pending] = useActionState(person ? updatePerson : addPerson, initial); return <form action={action} className="space-y-3 border-b border-border-subtle bg-surface-muted p-4">{person ? <input type="hidden" name="id" value={person.id} /> : null}<div className="grid gap-3 sm:grid-cols-2"><Field name="name" label="Full name" defaultValue={person?.name ?? ""} required /><Field name="email" label="Email" type="email" defaultValue={person?.email ?? ""} required /><label><span className="mb-1 block text-xs font-medium text-muted-foreground">Role</span><select name="role" defaultValue={person?.role ?? "staff"} className={inputClass}>{roles.map((role) => <option key={role.id} value={role.id}>{role.label}</option>)}</select></label><Field name="costRatePerHour" label="Cost rate / hour" type="number" defaultValue={String((person?.costRateCentsPerHour ?? 0) / 100)} /><label><span className="mb-1 block text-xs font-medium text-muted-foreground">Calendar colour</span><input name="color" type="color" defaultValue={person?.color ?? defaultColor(person?.id ?? "new-person")} className="h-11 w-full rounded-lg border border-border-strong bg-surface p-1" /></label><label className="flex items-center gap-3 pt-6 text-sm font-medium"><input name="isSchedulable" type="checkbox" defaultChecked={person?.isSchedulable ?? true} className="size-5 accent-primary" /> Can be assigned to phases</label></div><FormButtons pending={pending} editing={Boolean(person)} message={state.message} ok={state.ok} onClose={onClose} /></form>; }

function LeaveRow({ entry, people, canManage, leaveTypes, leaveStatuses }: { entry: LeaveEntry; people: Person[]; canManage: boolean; leaveTypes: Option[]; leaveStatuses: Option[] }) { const [editing, setEditing] = useState(false); const [deleting, startTransition] = useTransition(); const router = useRouter(); const person = people.find((item) => item.id === entry.userId); if (editing) return <LeaveForm entry={entry} people={people} leaveTypes={leaveTypes} leaveStatuses={leaveStatuses} onClose={() => setEditing(false)} />; return <div className="flex flex-wrap items-center justify-between gap-3 px-4 py-4"><div><p className="text-sm font-bold">{person?.name ?? "Deleted user"}</p><p className="mt-0.5 text-xs text-muted-foreground">{leaveTypes.find((type) => type.id === entry.type)?.label ?? entry.type} · {formatDate(entry.startsAt, true)} – {formatDate(entry.endsAt, true)} · {leaveStatuses.find((status) => status.id === entry.status)?.label ?? entry.status}{entry.reason ? ` · ${entry.reason}` : ""}</p></div>{canManage ? <div className="flex gap-2"><Button size="sm" onClick={() => setEditing(true)}>Edit</Button><Button size="sm" variant="danger" disabled={deleting} onClick={() => { if (window.confirm("Delete this leave or unavailability record?")) startTransition(async () => { await deleteLeave(entry.id); router.refresh(); }); }}><Trash2 className="size-3.5" /> Delete</Button></div> : null}</div>; }

function LeaveForm({ entry, people, leaveTypes, leaveStatuses, onClose }: { entry?: LeaveEntry; people: Person[]; leaveTypes: Option[]; leaveStatuses: Option[]; onClose: () => void }) { const [state, action, pending] = useActionState(entry ? updateLeave : addLeave, initial); return <form action={action} className="space-y-3 border-b border-border-subtle bg-surface-muted p-4">{entry ? <input type="hidden" name="id" value={entry.id} /> : null}<div className="grid gap-3 sm:grid-cols-2"><label><span className="mb-1 block text-xs font-medium text-muted-foreground">Person</span><select name="userId" required defaultValue={entry?.userId ?? ""} className={inputClass}><option value="" disabled>Select person…</option>{people.map((person) => <option key={person.id} value={person.id}>{person.name}</option>)}</select></label><label><span className="mb-1 block text-xs font-medium text-muted-foreground">Type</span><select name="type" defaultValue={entry?.type ?? "unavailable"} className={inputClass}>{leaveTypes.map((type) => <option key={type.id} value={type.id}>{type.label}</option>)}</select></label><label><span className="mb-1 block text-xs font-medium text-muted-foreground">Start date</span><input name="startsAt" required type="date" defaultValue={entry?.startsAt.slice(0, 10) ?? ""} className={inputClass} /></label><label><span className="mb-1 block text-xs font-medium text-muted-foreground">End date</span><input name="endsAt" required type="date" defaultValue={entry?.endsAt.slice(0, 10) ?? ""} className={inputClass} /></label><label><span className="mb-1 block text-xs font-medium text-muted-foreground">Status</span><select name="status" defaultValue={entry?.status ?? "approved"} className={inputClass}>{leaveStatuses.map((status) => <option key={status.id} value={status.id}>{status.label}</option>)}</select></label><Field name="reason" label="Notes" defaultValue={entry?.reason ?? ""} /></div><FormButtons pending={pending} editing={Boolean(entry)} message={state.message} ok={state.ok} onClose={onClose} /></form>; }

function FormButtons({ pending, editing, message, ok, onClose }: { pending: boolean; editing: boolean; message?: string; ok: boolean; onClose: () => void }) { return <div className="flex flex-wrap items-center gap-2"><Button type="submit" size="sm" variant="primary" disabled={pending}>{pending ? "Saving…" : editing ? "Save changes" : "Add"}</Button><Button type="button" size="sm" variant="ghost" onClick={onClose}>Cancel</Button>{message ? <p className={`text-xs ${ok ? "text-[var(--tone-emerald-fg)]" : "text-[var(--tone-rose-fg)]"}`}>{message}</p> : null}</div>; }
function Field({ name, label, defaultValue, type = "text", required = false }: { name: string; label: string; defaultValue: string; type?: string; required?: boolean }) { return <label><span className="mb-1 block text-xs font-medium text-muted-foreground">{label}</span><input name={name} required={required} type={type} defaultValue={defaultValue} className={inputClass} /></label>; }
function defaultColor(id: string) { const colors = ["#2563eb", "#7c3aed", "#db2777", "#d97706", "#059669", "#0891b2", "#4f46e5", "#be123c"]; let hash = 0; for (const char of id) hash = (hash * 31 + char.charCodeAt(0)) >>> 0; return colors[hash % colors.length]; }
